# Generated by Django 4.1.3 on 2022-12-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baizak', '0002_article_image_remove_images_name_delete_articles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
