# Generated by Django 4.1.3 on 2022-12-02 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baizak', '0004_event_rename_image_articleimage_eventimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='credits',
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='event',
            name='organization',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
