# Generated by Django 4.1.3 on 2022-12-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baizak', '0005_remove_event_credits_event_date_event_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='article',
            name='publication',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
