# Generated by Django 4.1.3 on 2022-12-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baizak', '0007_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='phone_number',
            field=models.CharField(default='', max_length=100),
        ),
    ]
